[tool.poetry]
name = "walletwatch-ml-backend"
version = "0.1.0"
description = ""
authors = [
  "Azis Rosyid <azisrosyid321@gmail.com>",
  "Muhammad Naufal <me@falkia34.dev>",
]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "2.3.3"
runpod = "1.12.0"
numpy = "1.26.4"
scikit-learn = "1.9.0"
onnxruntime = "1.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
